### ISSUE TITLE
Thanks for your amazing work :)

### ISSUE THREAD

**Issue by mm108** [chegewara/esp32-snippets#10]
@chegewara I was wondering if you have a PayPal donate button anywhere? I am sure your work has benefited many people - especially so the BLE related stuff. I'd like to get you couple of beers ( _Or Coffee if Beer doesn't work_ :) )

**Comment by chegewara** [comment]
Thanks.

This library is community effort and mostly is done by @nkolban. If you want to donate you can buy one of his book https://leanpub.com/bookstore?search=kolban or make donation to children organisation.

**Comment by mm108** [comment]
Sure chegewara. I actually brought Neil kolban's book on ESP32 on leanpub yesterday as a token of appreciation. I'll close this. Thanks once again.
